logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = '{{traefik.email}}'
storage = "/home/traefik/acme.json"
entryPoint = "https"
onDemand = false
onHostRule = true
caServer = "{{traefik.caServer}}"
[acme.dnsChallenge]
  provider = "{{traefik.provider}}"
  delayBeforeCheck = 60
[[acme.domains]]
  main = "{{traefik.main}}"
  sans = [ "{{traefik.sans}}" ]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{{traefik.sans}}"
watch = true
exposedByDefault = false
