---
- hosts: all
  serial: 2
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    app_name: traefik
    traefik_version: 1.7.12
  tasks:
    - name: Creates directory
      file:
        path: /home/{{ app_name }}
        state: directory

    - name: Traefik Config
      action: template src=template/traefik.toml dest=/home/{{ app_name }}/config.toml

    - name: Traefik Get
      get_url: 
        url: https://github.com/containous/traefik/releases/download/v{{traefik_version}}/traefik_linux-amd64
        dest: /usr/local/bin/traefik
        mode: 0775

    - name: Traefik Version
      command: bash -c "traefik version"
      register: traefik_version_check

    - debug: 
        msg: "{{ traefik_version_check.stdout }}"

    - name: Install supervisord
      apt: name=supervisor state=latest

    - name: Supervisor Config for {{ app_name }}
      action: template src=template/supervisor.ini dest=/etc/supervisor/conf.d/{{ app_name }}.conf
      notify:
        - restart app

  handlers:
    - name: restart app
      action: supervisorctl name={{ app_name }} state=restarted
